spring.application.name=Simple-Server
server.port=8081

#MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=users

#spring.profiles.active=dev

#Config Server (Getting Eureka Configuration)
spring.config.import=optional:configserver:http://localhost:8099

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#eureka.instance.prefer-ip-address: true
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true