server.port=8084
spring.application.name=API-Gateway
spring.profiles.active=dev
spring.config.import=optional:configserver:http://localhost:8083/,classpath:api-config.yml
spring.main.web-application-type=reactive
#datadog.metrix.export.api-key=3d0b3c0318541275b96b5407fcdbbc70
