spring.application.name=Redis-Server
server.port=8080

#spring.profiles.active=dev

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#Config Server (Getting Eureka Configuration)
spring.config.import=optional:configserver:http://localhost:8099/

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#eureka.instance.prefer-ip-address: true
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true